server:
  port: 8084
rocketmq:
  default: true
  comsumer:
    groupName: TopicTest
    namesrvAddr: localhost:9876
  provider:
    groupName: TopicTest
    namesrvAddr: localhost:9876
spring:
  application:
    name: TopicTest